### ISSUE TITLE
prebuilt ./anja: line 48: /home/milk/src/anja/__targets_rel_presc2m/anja: No such file or directory

### ISSUE THREAD

**Issue by milkmiruku** [milasudril/anja#112]
The prebuilt copy of anja in the repo gives me the error `prebuilt ./anja: line 48: /home/milk/src/anja/__targets_rel_presc2m/anja: No such file or directory`.

I'm on Arch and I believe I have the required runtime deps installed. I'll give building a go later after I've finished a large system upgrade.

**Comment by milasudril** [comment]
Thank you for participating. The file `anja` is a wrapper script that is used to start anja when compiled. So, to compile it:

 1. Install `maike`  (pull from https://github.com/milasudril/maike)
 2. Run `make`. This will compile 4 versions of anja, `rel_presc2m` being one of them. Notice that Anja has a large set of build-deps.
 3. Now ./anja should work. It will dispatch to the correct version for your CPU and if you want to be able to debug anja. It is interesting that it wanted to launch presc2m. This should mean that your CPU lacks some more advanced instructions. If you believe that your CPU has the required instructions for running the coreix target, open a new issue with your /proc/cpuinfo file. If it chose the wrong version, there is a bug in the wrapper script.

**Comment by milkmiruku** [comment]
Thanks for the clarification. I'm trying to build now. Might you be able to advise what would cause the following error?

```
./build.sh --configfiles=maikeconfig-base.json,maikeconfig-rel.json,maikeconfig-presc2m.json,maikeconfig-rel-presc2m.json
__maike_bin/maike
'python3' '--' 'versioninfo.py' '__targets_rel_presc2m' '.' '__targets_rel_presc2m/maikeconfig.json'
'bash' 'doc/index.sh' '__targets_rel_presc2m/doc/anja-usersguide.tar.gz' 'doc/index.xml' 'doc' '__targets_rel_presc2m/doc/logo_3.png' '__targets_rel_presc2m/doc/logo_2.png' '__targets_rel_presc2m/doc/logo_1.png' '__targets_rel_presc2m/doc/logo.png' '__targets_rel_presc2m/doc/message_info.svg' '__targets_rel_presc2m/doc/message_warning.svg' '__targets_rel_presc2m/doc/message_usererror.svg' '__targets_rel_presc2m/doc/message_error.svg' '__targets_rel_presc2m/doc/mainwindowstart.png' '__targets_rel_presc2m/doc/anja_layout.svg' '__targets_rel_presc2m/doc/led_stop.png' '__targets_rel_presc2m/doc/led_ready.png' '__targets_rel_presc2m/doc/statusarea.png' 'doc/statusarea.svg' '__targets_rel_presc2m/doc/led_off.png' '__targets_rel_presc2m/doc/led_wait.png' '__targets_rel_presc2m/doc/led_ready.png' '__targets_rel_presc2m/doc/portselector.png' '__targets_rel_presc2m/doc/led_stop.png' '__targets_rel_presc2m/doc/led_ready.png' '__targets_rel_presc2m/doc/led_ready.png' '__targets_rel_presc2m/doc/led_stop.png' '__targets_rel_presc2m/doc/waveformsettings.png' '__targets_rel_presc2m/doc/waveformtrim.png' '__targets_rel_presc2m/doc/playseq.svg' '__targets_rel_presc2m/doc/channels.png' '__targets_rel_presc2m/doc/led_stop.png' '__targets_rel_presc2m/doc/led_off.png' '__targets_rel_presc2m/doc/led_wait.png' '__targets_rel_presc2m/doc/led_off.png' '__targets_rel_presc2m/doc/session.png' '__targets_rel_presc2m/doc/led_off.png' '__targets_rel_presc2m/doc/led_off.png' '__targets_rel_presc2m/doc/led_wait.png' '__targets_rel_presc2m/doc/led_stop.png' '__targets_rel_presc2m/doc/led_ready.png' '__targets_rel_presc2m/doc/signalflow.svg' '__targets_rel_presc2m/doc/modinteract.svg' 'doc/format.css' 'doc/color.css' '__targets_rel_presc2m/doc/anja-usersguide.pdf'
doc/index.xml: Compilation failed with status 1.
make: *** [Makefile:4: release] Error 255
```

**Comment by milasudril** [comment]
Is this `bash` command the second command maike invokes or is this a retry? What is the output of

    make clean
    make

Here is a reference run: https://launchpadlibrarian.net/375167947/buildlog_ubuntu-bionic-amd64.anja_2.0.1-1milasudril1~bionic_BUILDING.txt.gz.

The html version of the manual is dependent on a working executable, so unless something is horribly broken, you should be able to start `__targets_rel_presc2m/anja`.

Why couldn't it build the html version of the manual? One possibility is that some scripts involved in compiling the pdf returns 0 when they should return a non-zero value. In this case maike will *assume* that all dependencies have been compiled, as all processes succeeded.

**Comment by milkmiruku** [comment]
[Here](https://gist.github.com/milkmiruku/15d3221e7b6331c1664a9166d4fc8c01) is the full output after a clean.

Below is the end of the output;

```
...
[32
chapter J.
[33 [34] (./anja-usersguide.aux) )
(see the transcript file for additional information)
Output written on anja-usersguide.pdf (42 pages).'bash' 'doc/index.sh' '__targets_rel_presc2m/doc/anja-usersguide.tar.gz' 'doc/index.xml' 'doc' '__targets_rel_presc2m/doc/logo_3.png' '__targets_rel_presc2m/doc/logo_2.png' '__targets_rel_presc2m/doc/logo_1.png' '__targets_rel_presc2m/doc/logo.png' '__targets_rel_presc2m/doc/message_info.svg' '__targets_rel_presc2m/doc/message_warning.svg' '__targets_rel_presc2m/doc/message_usererror.svg' '__targets_rel_presc2m/doc/message_error.svg' '__targets_rel_presc2m/doc/mainwindowstart.png' '__targets_rel_presc2m/doc/anja_layout.svg' '__targets_rel_presc2m/doc/led_stop.png' '__targets_rel_presc2m/doc/led_ready.png' '__targets_rel_presc2m/doc/statusarea.png' 'doc/statusarea.svg' '__targets_rel_presc2m/doc/led_off.png' '__targets_rel_presc2m/doc/led_wait.png' '__targets_rel_presc2m/doc/led_ready.png' '__targets_rel_presc2m/doc/portselector.png' '__targets_rel_presc2m/doc/led_stop.png' '__targets_rel_presc2m/doc/led_ready.png' '__targets_rel_presc2m/doc/led_ready.png' '__targets_rel_presc2m/doc/led_stop.png' '__targets_rel_presc2m/doc/waveformsettings.png' '__targets_rel_presc2m/doc/waveformtrim.png' '__targets_rel_presc2m/doc/playseq.svg' '__targets_rel_presc2m/doc/channels.png' '__targets_rel_presc2m/doc/led_stop.png' '__targets_rel_presc2m/doc/led_off.png' '__targets_rel_presc2m/doc/led_wait.png' '__targets_rel_presc2m/doc/led_off.png' '__targets_rel_presc2m/doc/session.png' '__targets_rel_presc2m/doc/led_off.png' '__targets_rel_presc2m/doc/led_off.png' '__targets_rel_presc2m/doc/led_wait.png' '__targets_rel_presc2m/doc/led_stop.png' '__targets_rel_presc2m/doc/led_ready.png' '__targets_rel_presc2m/doc/signalflow.svg' '__targets_rel_presc2m/doc/modinteract.svg' 'doc/format.css' 'doc/color.css' '__targets_rel_presc2m/doc/anja-usersguide.pdf'
doc/index.sh: line 29: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8): No such file or directory
Traceback (most recent call last):
  File "doc/makepage.py", line 603, in <module>
    main(sys.argv[1:])
  File "doc/makepage.py", line 538, in main
    tree=ET.parse(sys.stdin)
  File "/usr/lib/python3.6/xml/etree/ElementTree.py", line 1196, in parse
    tree.parse(source, parser)
  File "/usr/lib/python3.6/xml/etree/ElementTree.py", line 597, in parse
    self._root = parser._parse_whole(source)
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 6, column 14
Error: I/O errordoc/index.xml: Compilation failed with status 1.
make: *** [Makefile:4: release] Error 255
```

But `./anja` then runs, so not as much of a problem. Thanks again for the help!

**Comment by milasudril** [comment]
Ok, so you are missing th C.UTF-8 locale (which is *really* interesting, or does Arch call it something else?). Then Python cannot process the input xml file so the script fails. But, you have the manual as a PDF, as the input tex file can be generated by xsltproc (the html part was a bit more demanding due to lack of section numbering etc).
